import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1440px" },
    },
    extend: {
      fontFamily: {
        serif: ['"Canela Deck"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        sans: ['"Suisse Int\'l"', 'Inter', 'system-ui', 'sans-serif'],
        editorial: ['"Fraunces"', '"Cormorant Garamond"', 'Georgia', 'serif'],
        reading: ['"Newsreader"', 'Georgia', 'serif'],
      },
      spacing: {
        header: "clamp(6rem, 8vw, 8rem)",
        "section-sm": "clamp(3rem, 6vw, 5rem)",
        section: "clamp(4rem, 8vw, 7.5rem)",
        "section-lg": "clamp(5rem, 10vw, 10rem)",
        commerce: "clamp(1.5rem, 3vw, 2.5rem)",
      },
      maxWidth: {
        reading: "65ch",
      },
      transitionDuration: {
        "1000": "1000ms",
        "1200": "1200ms",
        "1400": "1400ms",
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        nav: {
          DEFAULT: "hsl(var(--nav-background))",
          foreground: "hsl(var(--nav-foreground))",
          hover: "hsl(var(--nav-hover))",
        },
        "paper-ivory": "hsl(var(--paper-ivory))",
        "paper-bright": "hsl(var(--paper-bright))",
        "paper-alt": "hsl(var(--paper-alt))",
        "ink": {
          DEFAULT: "hsl(var(--ink))",
          soft: "hsl(var(--ink-soft))",
        },
        line: "hsl(var(--line))",
        "signature-crimson": "hsl(var(--signature-crimson))",
        "signature-crimson-deep": "hsl(var(--signature-crimson-deep))",
        "material-sand": "hsl(var(--material-sand))",
        "material-sakura": "hsl(var(--material-sakura))",
        "material-peacock": "hsl(var(--material-peacock))",
        champagne: "hsl(var(--champagne))",
        jasmine: {
          DEFAULT: "hsl(var(--jasmine))",
          deep: "hsl(var(--jasmine-deep))",
        },
        sand: "hsl(var(--sand))",
        sakura: "hsl(var(--sakura))",
        "warm-white": "hsl(var(--warm-white))",
        "warm-white-bright": "hsl(var(--warm-white-bright))",
        "rasa-lac": "hsl(var(--rasa-lac))",
        "rasa-lac-secondary": "hsl(var(--rasa-lac-secondary))",
        "rasa-cream": "hsl(var(--rasa-cream))",
        "rasa-cream-bright": "hsl(var(--rasa-cream-bright))",
        "rasa-rose": "hsl(var(--rasa-rose))",
        "rasa-mulberry": "hsl(var(--rasa-mulberry))",
        "rasa-gold": "hsl(var(--rasa-gold))",
        "rasa-eucalyptus": "hsl(var(--rasa-eucalyptus))",
        "rasa-border": "hsl(var(--rasa-border))",
        "rasa-ink": "hsl(var(--rasa-ink))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-up": { from: { opacity: "0", transform: "translateY(24px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "drift": { "0%, 100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-6px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.8s ease-out both",
        "fade-up": "fade-up 1s cubic-bezier(0.22, 1, 0.36, 1) both",
        "drift": "drift 6s ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
